### ISSUE TITLE
ITN cube paper

### ISSUE THREAD

**Issue by bertozzivill** [bertozzivill/malaria-atlas-project#5]
See item 1 (here)[https://paper.dropbox.com/doc/Paper-Plan--AUOOWdmzAkxteP8FyDuh~O9OAg-hFB9rnpnhHUIxuxy5kSCW]. 

Bugs/updates whose effect has been TESTED:
- [ ] household size distributions (issue 3)
- [ ] running use gap with data to 2015 (issue 9)
- [ ] new emplogit function (issue 10)
- [ ] drop gap and gap3 before running complete.cases (issue 4)
- [ ] weight national access by household size when aggregating (issue 6)
- [ ] aggregate to pixel level before calculating access dev or use gap (issue 7)
- [ ] start calculating access and covariates from true month (issue 11)
- [ ] rerun with new survey data from Harry (issue 8)
- [ ] rerun with new covariates (issue 11)
